environment:
  name: Lab Environment Overview
install:
  name: Installing the *oc* client tool
  vars:
    DOWNLOAD_CLIENT_WINDOWS: "https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-windows.zip"
    DOWNLOAD_CLIENT_MAC: "https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-mac.zip"
    DOWNLOAD_CLIENT_LIN32: "https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-32bit.tar.gz"
    DOWNLOAD_CLIENT_LIN64: "https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-64bit.tar.gz"
    OC_VERSION: "oc v1.3.0\nkubernetes v1.3.0+52492b4"
  revisions:
    ocp:
      vars:
        DOWNLOAD_CLIENT_WINDOWS: <win link>
        DOWNLOAD_CLIENT_MAC: <mac link>
        DOWNLOAD_CLIENT_LIN32: <lin link>
        DOWNLOAD_CLIENT_LIN64: <lim link>
        OC_VERSION: <status>

smoketest:
  name: Smoke Testing the Environment
docker:
  name: Deploying our First Docker Image
routes:
  name: Creating Routes
remote-ops:
  name: Remote Operations
scaling:
  name: Scaling
jboss:
  name: Deploying Java Code on JBoss
databases:
  name: Adding a Database (MongoDB)
  requires:
    - jboss
codechanges:
  name: Using Source 2 Image for Code Changes
  requires:
    - databases
templates:
  name: Using Application Templates
quotas:
  name: Limiting application resource usage
run-as-non-root:
  name: Running a container as a non Root user
